In [1]:
import numpy as np

In [2]:
import tensorflow as tf

d:\1903\.venv\lib\site-packages\tensorflow\python\framework\dtypes.py:458: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
d:\1903\.venv\lib\site-packages\tensorflow\python\framework\dtypes.py:459: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
d:\1903\.venv\lib\site-packages\tensorflow\python\framework\dtypes.py:460: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
d:\1903\.venv\lib\site-packages\tensorflow\python\framework\dtypes.py:461: FutureWarning: Passing (type, 1) or '1type' as a synonym of type

In [3]:
s = 'hello world'
print(s)

hello world


In [ ]:
# 常量, 变量,,占位符

In [4]:
# 定义常量
hello = tf.constant('hello world')
hello

<tf.Tensor 'Const:0' shape=() dtype=string>

In [5]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [6]:
session = tf.Session()


In [8]:
# 使用session去执行代码
session.run(hello).decode()

'hello world'

In [9]:
session.close()

In [11]:
# 使用上下文管理器管理session
with tf.Session() as sess:
    print(sess.run(hello))

b'hello world'


In [12]:
sess.run(hello)

RuntimeError: Attempted to use a closed Session.

In [13]:
a = tf.constant(1)
b = tf.constant(2)
add = a + b


In [14]:
with tf.Session() as sess:
    print(sess.run(add))

3


In [15]:
# 定义占位符
a = tf.placeholder(dtype=tf.int16)
b = tf.placeholder(dtype=tf.int16)
add = a + b

In [18]:
with tf.Session() as sess:
    print(sess.run(add, feed_dict={a: 3, b:4}))

7


In [31]:
# 定义变量
a = tf.Variable(initial_value=1, dtype=tf.float64)

In [21]:
init = tf.global_variables_initializer()

In [22]:
init

<tf.Operation 'init' type=NoOp>

In [27]:
a = a + 1

In [28]:
with tf.Session() as sess:
    # 所有的变量在使用之前一定要进行显示的初始化
    sess.run(init)
    print(sess.run(a))
    print(sess.run(a + 1))
    print(sess.run(a))

2
3
2


In [ ]:
a += 1

In [30]:
a

<tf.Tensor 'add_5:0' shape=() dtype=int32>

In [32]:
add_1 = tf.assign_add(a, 1)
# = a += 1

In [38]:
assign_a = tf.assign(a, 10)

In [ ]:
+= -=

In [41]:
sub_a = tf.assign_sub(a, 5)

In [42]:
init = tf.global_variables_initializer()

In [43]:
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(add_1))
    print(sess.run(add_1))
    print(sess.run(add_1))
    print(sess.run(assign_a))
    print(sess.run(sub_a))

2.0
3.0
4.0
10.0
5.0


In [44]:
# 在tensorflow中实现数学运算
a = tf.constant(1)
b = tf.constant(2)
add = a + b
sub = a - b
mul = a * b
div = a / b

In [45]:
with tf.Session() as sess:
    print(sess.run(add))
    print(sess.run(sub))
    print(sess.run(mul))
    print(sess.run(div))

3
-1
2
0.5


In [47]:
# 更推荐tensorflow中的运算
a = tf.constant(1)
b = tf.constant(2)
add = tf.add(a,b)
sub = tf.subtract(a,b)
mul = tf.multiply(a,b)
div = tf.div(a,b)

In [48]:
with tf.Session() as sess:
    print(sess.run(add))
    print(sess.run(sub))
    print(sess.run(mul))
    print(sess.run(div))

3
-1
2
0


In [49]:
# 矩阵的点乘
a = tf.constant(np.random.randint(0,10, size=(3,4)))
b = tf.constant(np.random.randint(0,10, size=(4, 5)))
a_b = tf.matmul(a,b)

In [50]:
with tf.Session() as sess:
    print(sess.run(a_b))

[[146  92  43 140  68]
 [ 99  21  21  86  58]
 [124 118  79 134  96]]
